
tasks:
  - init: npm install
    command: npm run dev

ports:
  - port: 5000
    onOpen: open-preview
  - port: 35729
    onOpen: ignore
vscode:
  extensions:
    - svelte.svelte-vscode
    - eamodio.gitlens
